[package]
name = "gpui-papyru2"
version = "0.1.0"
publish = false
edition = "2024"

[dependencies]
gpui = { version = "*" }
gpui-macros  = { version = "*" }
gpui-component = { version = "*" } 
gpui-component-assets = { version = "*" } 

anyhow = "1.0.100"

