[package]
name = "papyru2"
version = "0.6.0"
publish = false
edition = "2024"

[dependencies]
gpui = { version = "*" }
gpui-macros  = { version = "*" }
gpui-component = { version = "*" } 
gpui-component-assets = { version = "*" } 
reqwest = { version = "0.12.15-zed", package = "zed-reqwest" }
sum-tree = { version = "0.2.0", package = "zed-sum-tree" }

anyhow = "1.0.100"
lsp-types = "0.97.0"
tree-sitter-navi = "0.2.2"
autocorrect = "2.14.2"
chrono = "0.4.42"
smol = "2.0.2"
color-lsp = "0.2.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.145"
toml = "0.8.19"
tracing-subscriber = "0.3.20"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59.0", features = ["Win32_Storage_FileSystem"] }
