[package]
name = "input"
version = "0.1.0"
publish = false
edition = "2024"

[dependencies]
gpui = { version = "*" }
gpui-macros  = { version = "*" }
gpui-component = { version = "*" } 
gpui-component-assets = { version = "*" } 

reqwest = { version = "0.12.15-zed", package = "zed-reqwest" }
sum-tree = { version = "0.2.0", package = "zed-sum-tree" }

anyhow = "1"
log = "0.4"
lsp-types = "0.97.0"
notify = "7.0.0"
raw-window-handle = "0.6.2"
ropey = { version = "=2.0.0-beta.1", features = [
    "metric_lines_lf",
    "metric_utf16",
] }
rust-i18n = "3"
schemars = "1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1"
smallvec = "1"
smol = "2"
tracing = "0.1.41"

[dependencies.windows]
features = ["Wdk", "Wdk_System", "Wdk_System_SystemServices"]
version = "0.58.0"
